import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from "../components/navbar/NavBar";
import Hero from "../components/hero/Hero";
import TherapyBanner from "../components/therapyBanner/TherapyBanner";
import useScrollPosition from "../hooks/useScrollPosition";

const Home: NextPage = () => {

    const scrollPosition = useScrollPosition();

    console.log(scrollPosition);

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavBar/>
        <Hero/>
      <main className={styles.main}>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
